name: 'DynamoDB Table Actions'
description: 'GitHub Action to perform actions on AWS Dynamodb tables'
inputs:
  table:  
    description: 'DynamoDB Table'
    required: true
  region:
    description: 'AWS Region'
    required: true
  action:
    description: 'Action'
    required: false
    default: 'query'    
  input:
    description: 'Input for the table action'
    required: true
  result-selector:
    description: 'Specify the vale of the columns name for the result, if not specified all items will be returned'
    required: false
outputs:
  items: 
    description: 'array with all matching items'
runs:
  using: 'node16'
  main: 'lib/index.js'