name: 'DynamoDB Query Action'
description: 'DynamoDB action to query items in DynamoDB'
inputs:
  table:  
    description: 'DynamoDB Table'
    required: true
  region:
    description: 'AWS Region'
    required: true
  input:
    description: 'DynamoDB Query command Input ( Serialized JSON format)'
    required: true
  result-selector:
    description: 'Specify the value of the colomns for the result, if not specified all items will be returned'
    required: false
outputs:
  items: 
    description: 'JSON with query result with all matching items'
runs:
  using: 'node16'
  main: 'lib/index.js'